DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS skill;
DROP TABLE IF EXISTS user;


CREATE TABLE job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job TEXT UNIQUE NOT NULL,
  popularity INTEGER NOT NULL
);

CREATE TABLE skill (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  skill TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
